#!/bin/bash
set -e
DIR=$(dirname $0)
export CLASSPATH="$DIR/../antlr4/antlr-4.9.3-complete.jar"
$DIR/../antlr4/antlr4 -o $DIR/java -lib $DIR/../antlr4 -no-listener -no-visitor classic_expression.g4
/usr/bin/javac $DIR/java/*.java
$DIR/../antlr4/antlr4 -o $DIR/py3 -Dlanguage=Python3 -visitor -no-listener $DIR/classic_expression.g4
